name: timer_rubik
description: "Aplicación para speedcubers con cronómetro, algoritmos y seguimiento de tiempos"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  camera: ^0.11.1
  geolocator: ^13.0.0
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0 
  flutter_blue_plus: ^1.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_rubik.PNG"  
  adaptive_icon_background: "#FFFFFF"  

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/banner.jpeg
    
    # Iconos de algoritmos OLL
    - assets/1.png
    - assets/2.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
    - assets/7.png
    - assets/8.png
    - assets/9.png
    - assets/10.png
    - assets/11.png
    - assets/13.png
    - assets/14.png
    - assets/15.png
    - assets/16.png
    - assets/17.png

